### ISSUE TITLE
Unable to sync AI Groups per the wiki

### ISSUE THREAD

**Issue by Will-Nichols** [fencr0c/fen_a3#17]
After working and reading all the wiki information regarding the usage of AIS Groups and how to setup the modules for a mission I am running into what may be a bug. I am attempting to sync the AI groups for the AIS Location module to cache them and the AI infantry groups are not allowing me to sync them to the AIS Groups module that I have placed down.

[https://github.com/fencr0c/fen_a3/wiki/3.-AIS](url) Reading the Quick Start for AIS. It says that I should be able to link it and I would think that it would/should have a sync line in the same manner that the  AIS Objects do in the editor.

**Comment by fencr0c** [comment]
Apologies for delay in responding.

AI groups only need to be sync'd with the AIS Group Module. By default AIS groups are assigned to the nearest AIS location. This can be override using the "Override AIS Location" option within the AIS Groups Module.

Simple demo available [here](https://www.dropbox.com/s/7pwlgtrad8cgaw7/gitHub_example_001.Tanoa.7z?dl=0)
