### ISSUE TITLE
Syncing AIS Groups Module to multiple units in group freezes dedicated server

### ISSUE THREAD

**Issue by Tommo-S** [fencr0c/fen_a3#23]
Hi,

One of our mission makers accidentally synced the pilot & copilot inside a helicopter to an AIS Group module. The error appears to freeze the dedicated server and it required restarting. I'm not sure how that happened, but would it be possible to add in a check to prevent it from occurring in the future? Either to validate the connection in 3DEN to make sure two units from the same group aren't synced twice, or for the AIS Group module to avoid acting twice on the same group?

This is a screenshot of the error while locally hosting the mission for debugging.  
![20181211232956_1](https://user-images.githubusercontent.com/42665574/49801177-95387c80-fd9d-11e8-954e-b3eefe040bb3.jpg)

Thanks.

**Comment by fencr0c** [comment]
Note to self...
Issue is within fn_moduleGroup.sqf calling fenAIS_fnc_group for each sync'd unit.

**Comment by Will-Nichols** [comment]
@Tommo-S Might have placed the entities as individuals instead of as a unit. I'd be interested in getting a copy of that mission just to see what someone else does to add to my todo/nottodo list.

**Comment by fencr0c** [comment]
Fixed and published to Workshop.
