### ISSUE TITLE
Request add condition to AIS location 

### ISSUE THREAD

**Issue by ahmed007boss** [fencr0c/fen_a3#48]
it will be nice if there is condition statement in  AIS location attributes , based on this condition if it true the activate will be spawn if it false the location will not activate

**Comment by fencr0c** [comment]
Should be able to do this using the AIS Location Module “Activating Trigger”.

Place down a trigger and give it a name e.g. trigger_1.
In the condition box of the trigger put your condition e.g. (A==B or B==C);
Finally, in the AIS Location module enter trigger_1 into the Activating Trigger box.

You can reduce the AIS Location Module Activation Radius to 0 if you only want the location to activate on the trigger.

**Comment by ahmed007boss** [comment]
yes i did this work around already , but it would be nice without using trigger
